### ISSUE TITLE
php binary not switching

### ISSUE THREAD

**Issue by michaelburtonray** [conradkleinespel/sphp-osx#4]
The switching the php binary (used to run the local development server among other things) is not included in this script. Would be super helpful to include it.

**Comment by conradkleinespel** [comment]
Hey @michaelburtonray ,

Thanks for taking the time to open an issue :+1: 

I'm not sure I understand what you mean though. Could you please give me an example of what isn't working at the moment ?

Cheers !

**Comment by michaelburtonray** [comment]
When I switch versions, the php binary doesn't always follow along. Here is a cli session fragment, I hope this makes sense

```
➜ which php
/usr/local/bin/php

➜ php -v
PHP 5.5.23 (cli) (built: Mar 23 2015 01:47:37)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies

➜ sphp 54
PHP version 54 found
Unlinking old binaries...
Linking new binaries...
Linking /usr/local/Cellar/php54/5.4.39... 40 symlinks created
Linking new modphp addon...
Updating version file...
Restarting system Apache...
Done.

➜ which php
/usr/local/bin/php

➜ php -v
PHP 5.4.39 (cli) (built: Mar 23 2015 01:44:05)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies

➜ php 56
Could not open input file: 56

➜ sphp 56
PHP version 56 found
Unlinking old binaries...
Linking new binaries...
Linking /usr/local/Cellar/php56/5.6.7... 40 symlinks created
Linking new modphp addon...
Updating version file...
Restarting system Apache...
Done.

➜ which php
/usr/bin/php

➜ php -v
PHP 5.5.14 (cli) (built: Sep  9 2014 19:09:25)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
➜ 
```

**Comment by michaelburtonray** [comment]
I think it's a $PATH issue, possibly on my end, because when I then do 
```
➜  /usr/local/bin/php -v
PHP 5.4.39 (cli) (built: Mar 23 2015 01:44:05)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies
```

however, /usr/local/bin is before /usr/bin in my $PATH

```
➜  echo $PATH
/Users/michaelburtonray/.rvm/gems/ruby-2.2.0/bin
/Users/michaelburtonray/.rvm/gems/ruby-2.2.0@global/bin
/Users/michaelburtonray/.rvm/rubies/ruby-2.2.0/bin
/usr/local/heroku/bin
/usr/local/mysql/bin
/usr/local/opt/php56/bin
/usr/local/bin
/usr/local/sbin
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
/opt/X11/bin
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
/usr/local/share/npm/bin
/opt/X11/bin
/usr/local/mysql/bin
/Users/michaelburtonray/bin
/Users/michaelburtonray/.rvm/bin

```

So I'm not sure why it uses /usr/bin/php before /usr/local/bin/php :-/

**Comment by conradkleinespel** [comment]
Ah alright ! Interesting stuff ! :+1: 

It seems like this [is related to Bash in general](http://askubuntu.com/questions/300603/bash-refuses-to-execute-correct-binary).

Can you confirm if adding `hash -r` at the end of the `sphp` script fixes this issue ? I don't have access to a Mac (with OSX) right now, so I can't verify this.

**Comment by conradkleinespel** [comment]
Hello @michaelburtonray,

This issue has been open for a long time. I just checked once more. This is indeed related to how Bash caches paths of executables. I don't think there is a way to fix this within `sphp`.

Here are 2 options though:
- Add `set +h` in your `~/.bashrc` or `~/.profile` file. This will disable the executable path cache in Bash. However, this might slow down your Bash.
- After you use `sphp`, enter the command `hash -r` in your shell. This will clear the executable path cache only once.

I hope this helps. And as always, don't hesitate to reply or send me an email if you have any further questions.

Best regards,
Conrad
